conditional access operators
wixoaGit/OpenDream pull request #116
Opened 2021-05-26 03:51 UTC by willox

This adds `?.`.

When used on the LHS of an assignment (`=`, `+=`, etc.)`, the entire assignment will evaluate to null without the RHS executing.

`x?.y.z` will always result in a runtime if x is null (as `null.z` is performed.) This behaviour varies depending on which version of BYOND you are using: http://www.byond.com/forum/post/2667038?hla=Willox#comment25786061. I chose the sane one.

2021-05-26 03:54 UTC, willox commented
I also touched up a few of the opcode handlers which were pushing/popping different amounts of values depending on which branch they took. Caused problems in situations like `return L[2] *= 15 `, where null would be returned instead of the list's new value.

2021-05-26 06:26 UTC, ike709 commented
Conflicts

2021-05-26 18:19 UTC, willox commented
conflicts fixed

2021-05-27 00:52 UTC, wixoaGit requested changes

2021-05-27 00:52 UTC, wixoaGit commented on OpenDreamShared/Compiler/Token.cs
> +        DM_Preproc_Punctuator_Colon,
Keep these in alphabetic order

2021-05-27 01:00 UTC, willox commented
Would you like me to pull my const_expr branch onto this before merging it? It cleans up the expressions namespace into separate files and adds support for (most) constant expressions in switch statement conditions.

https://github.com/willox/OpenDream/compare/conditionals...const_expr

Otherwise I'll just PR it after this is merged.

2021-05-27 01:00 UTC, wixoaGit requested changes

2021-05-27 01:00 UTC, wixoaGit commented on OpenDreamShared/Compiler/Token.cs
> +        DM_QuestionColon,
These too

2021-05-27 01:01 UTC, wixoaGit commented
Make that another PR

2021-05-27 01:03 UTC, wixoaGit approved these changes

2021-05-27 01:06 UTC, merged