Include file path fix for linux
wixoaGit/OpenDream pull request #147
Opened 2021-06-16 13:28 UTC by mumencoder

2021-06-16 19:30 UTC, ZeWaka approved these changes

2021-06-16 19:42 UTC, wixoaGit requested changes

2021-06-16 19:42 UTC, wixoaGit commented on OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessor.cs
> +            }
```suggestion
            file = file.Replace('\\', Path.DirectorySeparatorChar);
```

2021-06-17 00:09 UTC, wixoaGit approved these changes

2021-06-17 03:21 UTC, merged