Implements actual invisibility
wixoaGit/OpenDream pull request #241
Opened 2021-07-18 20:16 UTC by ike709

https://streamable.com/8zbc1n

2021-07-18 20:51 UTC, wixoaGit requested changes
`SeeInvisible` needs to be serialized in `PacketFullGameState`'s `ReadClientSection` and `WriteClientSection`

2021-07-18 20:51 UTC, wixoaGit commented on OpenDreamShared/Net/Packets/PacketDeltaGameState.cs
> +                    stream.WriteByte(ClientDelta.NewSeeInvisible.Value);
```suggestion
                    stream.WriteByte((byte)ClientValueID.SeeInvisible);
                    stream.WriteByte(ClientDelta.NewSeeInvisible.Value);
```

2021-07-18 21:10 UTC, ike709 commented
Done.

2021-07-19 01:35 UTC, wixoaGit requested changes

2021-07-19 01:35 UTC, wixoaGit commented on OpenDreamShared/Net/Packets/PacketDeltaGameState.cs
> +                    stream.WriteByte((byte)ClientDelta.NewSeeInvisible.Value);
You have to write which value this is before actually writing the value
```suggestion
                    stream.WriteByte((byte)ClientValueID.SeeInvisible);
                    stream.WriteByte((byte)ClientDelta.NewSeeInvisible.Value);
```

2021-07-19 01:48 UTC, ike709 commented
There

2021-07-19 01:51 UTC, wixoaGit approved these changes

2021-07-19 01:51 UTC, merged