Improves raw string handling
wixoaGit/OpenDream pull request #380
Opened 2021-09-08 14:47 UTC by ike709

Raw strings containing newlines no longer error. This fixes 21 errors on modern TG.

The strings will also no longer contain the tabs from code indentation.

2021-09-09 21:56 UTC, ike709 commented
Slight issue: This doesn't handle raw strings that contain `{}` inside of them

2021-09-24 00:55 UTC, wixoaGit requested changes

2021-09-24 00:55 UTC, wixoaGit commented on OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
> +                        }
It'd be better to instead have two separate `CreateToken` calls after building the text for each type of raw string.
`token = CreateToken(TokenType.DM_Preproc_ConstantString, text, text.Substring(2, text.Length - 3));` after line 227, and
`token = CreateToken(TokenType.DM_Preproc_ConstantString, text, text.Substring(3, text.Length - 5));` after line 219.

2021-09-24 00:55 UTC, wixoaGit commented on OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
> +                        if (delimiter == '{')
A long raw string needs to start with `@{"`, not just `@{`

2021-09-24 00:55 UTC, wixoaGit commented on OpenDreamShared/Compiler/DMPreprocessor/DMPreprocessorLexer.cs
> +                                if (c == '}' && prev == '\"')
This would break with `@{"}`

2021-11-04 18:35 UTC, ike709 commented
I cba to finish this but someone should.

2021-11-04 18:35 UTC, closed without merging