Implements implicit `in world` loops
wixoaGit/OpenDream pull request #387
Opened 2021-09-09 01:32 UTC by ike709

Stuff like `for(var/mob/M)`

2021-09-10 15:47 UTC, wixoaGit commented
These loops are not implicit `in world` loops. They loop through every existing instance of a type, wether or not it's in the world. For example, `for (var/client/C)` loops through every client, despite them not being in `world.contents`.

https://github.com/wixoaGit/OpenDream/issues/50#issuecomment-865178884

2021-09-10 15:52 UTC, ike709 commented
According to the docs, a for loop will by default loop through the world. Clients and datums are a special case and a separate issue.

![image](https://user-images.githubusercontent.com/5714543/132881860-9cf8d9b6-92c6-496d-a855-16b40028df5c.png)

2021-09-10 22:09 UTC, wixoaGit commented
I suspect the docs aren't being entirely correct here. It works for _any_ type, there is no special case for just clients and datums.

I'd rather this not silently create a non-working loop for types that aren't atoms.

2021-09-12 20:23 UTC, ike709 commented on OpenDreamShared/Compiler/DM/DMParser.cs
> +                        var path = new DreamPath(variableDeclaration.Type.ToString());
Not sure why but the compiler hated it when I used `variableDeclaration.Type` directly.

2021-09-12 22:02 UTC, ike709 commented on DMCompiler/DM/Visitors/DMVisitorProcBuilder.cs
> +
```suggestion
```

2021-09-13 00:50 UTC, wixoaGit requested changes

2021-09-13 00:50 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
> +                    if (rangeBegin is not DMASTConstantNull)
This allows you to do an implicit world loop if you do `for (var/atom/A = null)`. This does not work in byond.

2021-09-13 00:50 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
> +                    if (rangeBegin is not DMASTConstantNull && rangeEnd == null) Error("Expected an expression");
This would allow `for (var/i = null to)`

2021-09-13 02:47 UTC, wixoaGit approved these changes

2021-09-13 02:47 UTC, merged