allow all statement expressions in for loop initializers
wixoaGit/OpenDream pull request #414
Opened 2021-09-19 00:55 UTC by mumencoder

this happens occasionally in the unmodified ss13 repos, where the statement expression has side effects as well

2021-11-18 01:33 UTC, wixoaGit commented
I'd rather not use any lookahead if possible (`SavePosition()`/`RestorePosition()`). Can this be done another way?

2022-06-15 23:59 UTC, ike709 commented
This fixes #527

2022-07-08 15:01 UTC, wixoaGit requested changes

2022-07-16 22:15 UTC, wixoaGit approved these changes

2022-07-16 22:15 UTC, merged