change direct to lax deref for certain expressions
wixoaGit/OpenDream pull request #440
Opened 2021-10-29 00:11 UTC by mumencoder

test case:
```

#include "map.dmm"
#include "interface.dmf"

/obj
    inner
        var/ele2 = 4

    var/ele = 2
    var/innerobj

    var/obj/inner/innerobj_ty

    proc/inner_proc()
        return new /obj
    proc/elefn()
        return 3

/proc/new_obj()
    return new /obj

/world/New()
    ASSERT(new_obj().ele == 2)
    ASSERT(new_obj()?.ele == 2)
    ASSERT(new_obj().inner_proc().ele == 2)
    ASSERT(new_obj()?.inner_proc()?.ele == 2)

    var/obj/o2 = new /obj
    ASSERT(o2.inner_proc().elefn() == 3)
    ASSERT(o2?.inner_proc()?.elefn() == 3)

    o2.innerobj_ty = new /obj/inner
    ASSERT(o2:innerobj_ty.ele2 == 4)

    var/list/l = newlist(/obj)
    ASSERT(l[1].ele == 2)
    ASSERT(l[1].elefn() == 3)

    l[1].innerobj = new /obj/inner
    ASSERT(l[1].innerobj.ele2 == 4)

    var/o
    // This is still not allowed
    //world.log << "[o.ele]"
    //world.log << "[o.elefn()]"

    shutdown()
```

2021-10-30 21:17 UTC, mumencoder commented
fixes #145

2021-11-26 03:40 UTC, wixoaGit requested changes

2021-11-26 03:40 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
> +            return false;
A switch would be more readable, imo
```suggestion
            switch (astNode.Expression) {
                case DMASTDereference deref when deref.Type == DMASTDereference.DereferenceType.Search:
                case DMASTProcCall when expr.Path == null:
                case DMASTDereferenceProc:
                case DMASTListIndex:
                    return true;
                case DMASTDereference deref when expr is Dereference _deref:
                    return DirectConvertable(_deref._expr, deref);
                default: return false;
            }
```

2021-11-26 19:12 UTC, wixoaGit approved these changes

2021-11-26 19:12 UTC, merged