More stubs for DMStandard
wixoaGit/OpenDream pull request #443
Opened 2021-10-30 14:48 UTC by mumencoder

2021-10-31 00:05 UTC, wixoaGit requested changes

2021-10-31 00:05 UTC, wixoaGit commented on DMCompiler/DMStandard/UnsortedAdditions.dm
> +	proc/_dm_db_close()
These are not valid types
```suggestion
```

2021-10-31 00:05 UTC, wixoaGit commented on DMCompiler/DMStandard/UnsortedAdditions.dm
> +	var/filters = list()
I worry that stubbing vars like this is going to lead to silently broken code. I'd like to have some way of flagging vars like this as unimplemented, similar to what we have for procs right now. This was brought up in #368.

2021-11-11 20:25 UTC, ike709 commented
You can now flag unimplemented vars by giving them the `opendream_unimplemented` astype like `var/filters = list() as opendream_unimplemented`

2021-11-18 03:05 UTC, ike709 commented on DMCompiler/DMStandard/Types/Atoms/Movable.dm
> +	var/glide_size
```suggestion
	var/list/locs = list() as opendream_unimplemented
	var/glide_size as opendream_unimplemented
```
```suggestion
	var/list/locs = list()
	var/glide_size
```

2021-11-18 03:05 UTC, ike709 commented on DMCompiler/DMStandard/Types/Atoms/_Atom.dm
> +	var/list/vis_contents = list()
```suggestion
	var/filters = list() as opendream_unimplemented
	var/appearance as opendream_unimplemented
	var/appearance_flags as opendream_unimplemented
	var/maptext_width as opendream_unimplemented
	var/maptext_height as opendream_unimplemented
	var/maptext_x = 32 as opendream_unimplemented
	var/maptext_y = 32 as opendream_unimplemented
	var/pixel_x as opendream_unimplemented
	var/pixel_y as opendream_unimplemented
	var/pixel_z as opendream_unimplemented
	var/pixel_w as opendream_unimplemented
	var/step_x as opendream_unimplemented
	var/step_y as opendream_unimplemented
	var/render_source as opendream_unimplemented
	var/bound_width as opendream_unimplemented
	var/bound_height as opendream_unimplemented
	var/mouse_drag_pointer as opendream_unimplemented
	var/mouse_drop_pointer as opendream_unimplemented
	var/render_target as opendream_unimplemented
	var/vis_flags as opendream_unimplemented
	var/vis_locs = list() as opendream_unimplemented
	var/list/vis_contents = list() as opendream_unimplemented
```

2021-11-18 03:06 UTC, ike709 commented on DMCompiler/DMStandard/Types/Client.dm
> +	var/glide_size
```suggestion
	var/color = 0 as opendream_unimplemented
	var/control_freak as opendream_unimplemented
	var/mouse_pointer_icon as opendream_unimplemented
	var/preload_rsc = 1 as opendream_unimplemented
	var/fps = 0 as opendream_unimplemented
	var/dir = NORTH as opendream_unimplemented
	var/gender = "neuter" as opendream_unimplemented
	var/glide_size as opendream_unimplemented
```

2021-11-18 03:07 UTC, ike709 commented on DMCompiler/DMStandard/Types/World.dm
> +	var/host
```suggestion
	var/map_cpu = 0 as opendream_unimplemented
	var/hub as opendream_unimplemented
	var/hub_password as opendream_unimplemented
	var/reachable as opendream_unimplemented
	var/game_state as opendream_unimplemented
	var/host as opendream_unimplemented
```

2021-11-18 03:07 UTC, ike709 commented on DMCompiler/DMStandard/Types/Sound.dm
> +	var/len
```suggestion
	var/environment as opendream_unimplemented
	var/echo as opendream_unimplemented
	var/len as opendream_unimplemented
```
```suggestion
	var/environment
	var/echo
	var/len
```

2021-11-18 03:07 UTC, ike709 commented on DMCompiler/DMStandard/Types/Mutable_Appearance.dm
> +	var/screen_loc
```suggestion
	var/animate_movement = 1 as opendream_unimplemented
	var/screen_loc as opendream_unimplemented
```

2021-11-18 03:08 UTC, ike709 commented on DMCompiler/DMStandard/Types/Image.dm
> +	var/list/filters = list()
```suggestion
	var/alpha = 255
	var/appearance as opendream_unimplemented
	var/appearance_flags = 0 as opendream_unimplemented
	var/blend_mode = 0 as opendream_unimplemented
	var/color = "#FFFFFF"
	var/desc = null
	var/gender = "neuter" as opendream_unimplemented
	var/infra_luminosity = 0 as opendream_unimplemented
	var/invisibility = 0 as opendream_unimplemented
	var/list/filters = list() as opendream_unimplemented
```

2021-11-18 03:09 UTC, ike709 commented on DMCompiler/DMStandard/Types/Image.dm
> +	var/override = 1 //TODO
```suggestion
	var/luminosity = 0 as opendream_unimplemented
	var/maptext = "i" as opendream_unimplemented
	var/maptext_width = 32 as opendream_unimplemented
	var/maptext_height = 32 as opendream_unimplemented
	var/maptext_x = 0 as opendream_unimplemented
	var/maptext_y = 0 as opendream_unimplemented
	var/mouse_over_pointer = 0 as opendream_unimplemented
	var/mouse_drag_pointer = 0 as opendream_unimplemented
	var/mouse_drop_pointer = 1 as opendream_unimplemented
	var/mouse_drop_zone = 0 as opendream_unimplemented
	var/mouse_opacity = 1
	var/name = "image"
	var/opacity = 0 as opendream_unimplemented
	var/list/overlays = list()
	var/override = 1 as opendream_unimplemented
```

2021-11-18 03:10 UTC, ike709 commented on DMCompiler/DMStandard/Types/Image.dm
> +	var/text = "i"
```suggestion
	var/pixel_w = 0 as opendream_unimplemented
	var/pixel_z = 0 as opendream_unimplemented
	var/plane = FLOAT_PLANE as opendream_unimplemented
	var/render_source as opendream_unimplemented
	var/render_target as opendream_unimplemented
	var/suffix as opendream_unimplemented
	var/text = "i" as opendream_unimplemented
```

2021-11-18 03:10 UTC, ike709 commented on DMCompiler/DMStandard/Types/Image.dm
> +	var/list/vis_contents = list()
```suggestion
	var/vis_flags = 0 as opendream_unimplemented

	var/bound_width as opendream_unimplemented
	var/bound_height as opendream_unimplemented
	var/name
	var/x
	var/y
	var/z
	var/list/filters = list() as opendream_unimplemented
	var/list/vis_contents = list() as opendream_unimplemented
```

2021-11-18 03:11 UTC, ike709 commented
Should be able to just commit all of those code suggestions and merge master and this PR will be good to go.

2021-11-18 04:19 UTC, ike709 commented
conflicts

2021-11-18 20:10 UTC, merged