Adds a partial `rgb2num()` implementation
wixoaGit/OpenDream pull request #445
Opened 2021-10-31 19:37 UTC by ike709

Adds `rgb2num()` except it only supports `COLORSPACE_RGB`.

http://www.byond.com/docs/ref/#/proc/rgb2num

2021-10-31 19:38 UTC, ike709 commented on OpenDreamShared/Dream/IconAppearance.cs
```suggestion
```

2021-11-17 02:32 UTC, wixoaGit requested changes

2021-11-17 02:34 UTC, ZeWaka commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                list.AddValue(new DreamValue(int.Parse(color.Substring(6, 2), NumberStyles.HexNumber)));
6?

2021-11-17 02:51 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                list.AddValue(new DreamValue(int.Parse(color.Substring(6, 2), NumberStyles.HexNumber)));
That's the alpha component

2021-11-17 15:29 UTC, wixoaGit approved these changes

2021-11-17 15:29 UTC, merged