[RT] Updates the readme for when we finally make RT the main branch
wixoaGit/OpenDream pull request #454
Opened 2021-11-04 03:40 UTC by ike709

2021-11-04 04:05 UTC, ZeWaka approved these changes

2021-11-04 04:05 UTC, ZeWaka commented on README.md
> +The compiler and server should work fine for Linux-based machines. The client should also work fine on Linux but none of the developers use it. More details and potentially useful troubleshooting for
lolololol

2021-11-05 16:47 UTC, wixoaGit requested changes

2021-11-05 16:47 UTC, wixoaGit commented on README.md
> +The compiler and server should work fine for Linux-based machines. The client should also work fine on Linux but none of the developers use it. More details and potentially useful troubleshooting for
The LINUX_FAQ.md only contains outdated information about CEF and setup. I'm removing it.

This line in the readme was meant to point out that one piece of the software was incompatible with Linux, which is no longer the case. Removing it entirely seems best.

2021-11-05 18:34 UTC, ike709 commented on README.md
> +The compiler and server should work fine for Linux-based machines. The client should also work fine on Linux but none of the developers use it. More details and potentially useful troubleshooting for
```suggestion
All parts of OpenDream should work fine on Windows and Linux, though the latter is not used as much and therefore isn't as thoroughly tested.
```

2021-11-05 18:35 UTC, ike709 commented
Tweaked the linux mention to just say we don't test it as much, which is accurate.

2021-11-06 01:58 UTC, wixoaGit approved these changes

2021-11-06 01:59 UTC, merged