Implements unimplemented warnings for vars
wixoaGit/OpenDream pull request #459
Opened 2021-11-09 21:52 UTC by ike709

Closes #368 

Trying to access or override a var flagged as unimplemented will throw a compiler warning.

Ex: `var/test as opendream_unimplemented`

2021-11-10 04:49 UTC, wixoaGit requested changes

2021-11-10 04:49 UTC, wixoaGit commented on DMCompiler/DM/DMObject.cs
> +                if (variable.Value.ValType == DMValueType.Unimplemented)
```suggestion
                if ((variable.Value.ValType & DMValueType.Unimplemented) == DMValueType.Unimplemented)
```

2021-11-10 04:49 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMObjectBuilder.cs
> +                    if (variable.Value is not null && variable.Value.ValType == DMValueType.Unimplemented)
```suggestion
                    if ((variable.Value?.ValType & DMValueType.Unimplemented) == DMValueType.Unimplemented)
```

2021-11-10 04:49 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMObjectBuilder.cs
> +                        Program.Warning(new CompilerWarning(null, $"{variable.Type}.{variable.Name} is not implemented and will have unexpected behavior"));
`variable.Type` is always null here. The way that variable overrides currently work, we don't know anything about the variable being overriden.

2021-11-10 04:49 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
> +                            varDef.ValType = val;
Move this to `DMASTObjectVarDefinition`'s constructor

2021-11-11 20:14 UTC, ike709 commented
Done

2021-11-11 20:23 UTC, wixoaGit approved these changes

2021-11-11 20:23 UTC, merged