Adds support for label blocks
wixoaGit/OpenDream pull request #466
Opened 2021-11-17 20:18 UTC by ike709

Fixes #408 

Adds support for label blocks and using continue/break in them.

This survived extremely basic testing but could probably use more rigorous BYOND parity testing.

2021-11-20 01:26 UTC, wixoaGit requested changes

2021-11-20 01:26 UTC, wixoaGit commented on DMCompiler/DM/DMProc.cs
> +                Jump(label.Identifier + "_start");
This doesn't continue a `for` loop properly. A `continue` needs to jump to a for's incrementor, which is at the end of the loop just before it jumps to the beginning.

A quirk to take note of is that label bodies can contain more than just a loop, and `continue label` will always continue the first loop in the body. `break label` will always exit the label body entirely.
```
var/i = 1
a:
	world.log << "A"
	for (,TRUE,i++)
		world.log << i
		break a
	world.log << "B"
sleep(10)
continue a
```
Outputs:
```
A
1
2
3
...
```

2021-11-20 01:26 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
>                  return new DMASTProcStatementBreak();
```suggestion
                DMASTExpression label = Expression();
                
                return new DMASTProcStatementBreak(label as DMASTIdentifier);
```

2021-11-20 01:26 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
>                  return new DMASTProcStatementContinue();
```suggestion
                DMASTExpression label = Expression();
                
                return new DMASTProcStatementContinue(label as DMASTIdentifier);
```

2021-11-23 22:53 UTC, wixoaGit requested changes

2021-11-23 22:53 UTC, wixoaGit commented on OpenDreamShared/Compiler/DM/DMParser.cs
> +                body = new DMASTProcBlockInner(new DMASTProcStatement[] { statement });
```suggestion
                if (statement != null) body = new DMASTProcBlockInner(new DMASTProcStatement[] { statement });
```

2021-11-23 22:53 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMProcBuilder.cs
> +                    _proc.AddLabel(statementLabel.Name + "_start");
This label is not used at all
```suggestion
```

2021-11-23 22:53 UTC, wixoaGit commented on DMCompiler/DM/DMProc.cs
> +                for (var i = labelList.IndexOf(codeLabel) + 2; i < labelList.Count; i++)
For the previous suggestion
```suggestion
                for (var i = labelList.IndexOf(codeLabel) + 1; i < labelList.Count; i++)
```

2021-11-24 01:15 UTC, ike709 commented
Reviews addressed

2021-11-24 01:26 UTC, wixoaGit approved these changes

2021-11-24 01:26 UTC, merged