Vibe checks a ton of `GetValueAsString()` uses
wixoaGit/OpenDream pull request #542
Opened 2021-12-18 03:37 UTC by ike709

Not all of them, just most of them.

Values are derived from BYOND's handling of `null` being passed except where otherwise noted.

2021-12-22 06:26 UTC, wixoaGit requested changes

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.Null;
This should return the argument unchanged.

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return new DreamValue(0);
`nonspantext("A", null)` is giving me `1`

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return new DreamValue("");
`replacetext("ABBC", "B", null)` is giving me `AC`

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.Null;
`replacetext("ABABC", null, "B")` is giving me `ABBBABBBC` (???)

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                throw new CancellingRuntime("bad color");
```suggestion
                throw new Exception("bad color");
```

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.Null;
This has the same issues as `replacetext()`

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                    return new DreamValue(0);
`roll(null)` gives `1`, though the 2-arg variant of this proc gives `0`
```suggestion
                    return new DreamValue(1);
```

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +               !arguments.GetArgument(1, "Delimiter").TryGetValueAsString(out var delimiter))
A null delimiter gives you a list of every character in the text.

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.Null;
If text is not a string then empty text is written to the file. If the file is null, `0` is returned.

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return new DreamValue("");
A null format argument returns a string in the format of `Thu Dec 30 15:13:20 1999`

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.Null;
This should return the argument unchanged, same as `lowertext()`

2021-12-22 06:26 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            }
`url_encode()` turns any value given into a string
```suggestion
            string plainText = arguments.GetArgument(0, "PlainText").Stringify();
```

2021-12-23 06:55 UTC, ike709 commented
Reviews addressed, I think.

2021-12-23 17:59 UTC, ike709 commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            if (!arguments.GetArgument(1, "Needle").TryGetValueAsString(out var needle))
```suggestion
            //TODO: Regex support
            if (!arguments.GetArgument(1, "Needle").TryGetValueAsString(out var needle))
```

2021-12-23 18:00 UTC, ike709 commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            if (!arguments.GetArgument(1, "Needle").TryGetValueAsString(out var needle))
```suggestion
            //TODO: Regex support
            if (!arguments.GetArgument(1, "Needle").TryGetValueAsString(out var needle))
```

2022-01-08 22:36 UTC, wixoaGit requested changes

2022-01-08 22:36 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            //TODO: Regex support
```suggestion
            //TODO: Regex support
```

2022-01-08 22:36 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                path = Path.GetDirectoryName(IoCManager.Resolve<IConfigurationManager>().GetCVar(OpenDreamCVars.JsonPath)) + Path.DirectorySeparatorChar;
```suggestion
                path = IoCManager.Resolve<DreamResourceManager>().RootPath + Path.DirectorySeparatorChar;
```

2022-01-09 05:25 UTC, ike709 commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            //TODO: Regex support
```suggestion
            //TODO: Regex support
```

2022-01-09 05:40 UTC, wixoaGit approved these changes

2022-01-09 05:40 UTC, merged