Make bad ..() calls a warning instead of an error
wixoaGit/OpenDream pull request #579
Opened 2022-02-02 06:45 UTC by ike709

Bad DM code has too much of this. If we ever make a clone of C# pragmas we could consider having it default as an error.

2022-02-02 14:50 UTC, wixoaGit requested changes

2022-02-02 14:50 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Procs.cs
> +                DMCompiler.Warning(new CompilerWarning(Location, "Cannot call parents via ..() in a proc definition"));
```suggestion
                DMCompiler.Warning(new CompilerWarning(Location, "Calling parents via ..() in a proc definition does nothing"));
```

2022-02-02 21:38 UTC, ZeWaka commented
😭

2022-02-03 01:43 UTC, wixoaGit approved these changes

2022-02-03 01:44 UTC, merged