Makes bad compiler args into compiler warnings
wixoaGit/OpenDream pull request #601
Opened 2022-03-02 09:08 UTC by ike709

2022-03-06 22:23 UTC, wixoaGit commented
Why is this preferable? It seems to me that if you make a mistake in the arguments you wouldn't want the compiler to go on.

2022-03-06 22:29 UTC, ike709 commented
Because I'm tired of needing to remember to remove `--experimental-preproc` from all of my Rider configurations.

2022-03-24 03:47 UTC, ike709 commented
TODO: Add a flag to cope with bad flags.

2022-03-25 03:16 UTC, wixoaGit requested changes

2022-03-25 03:16 UTC, wixoaGit commented on DMCompiler/Program.cs
> +                            if(skipBad || args.Contains("--skip-bad-args")) {
The `skipBad` variable can be removed if you're just going to end up doing `args.Contains("--skip-bad-args")` anyways.

2022-03-25 03:19 UTC, wixoaGit commented on DMCompiler/Program.cs
> +                            if(skipBad || args.Contains("--skip-bad-args")) {
That or initialize `skipBad` to be the Contains call

2022-03-25 11:02 UTC, wixoaGit approved these changes

2022-03-25 11:02 UTC, merged