Implements `background`
wixoaGit/OpenDream pull request #605
Opened 2022-03-03 06:51 UTC by ike709

It... just works?

2022-03-09 04:55 UTC, wixoaGit commented
Does the correct behavior for background look like this:
```
for(var/i in 1 to 3)
    world.log << i
    sleep(-1)
```
or this?
```
for(var/i in 1 to 3)
    world.log << i
sleep(-1)
```

The DM reference states `It would only ever be interrupted at the end of the for or while loops.`

2022-03-09 05:10 UTC, ike709 commented
> You could achieve a similar thing by sprinkling calls to sleep(0) or sleep(-1) in the "working" part of the loop.

This implies the former, IMO.

Also it seems like it wouldn't be that useful if it applied _outside_ of the looping

2022-03-09 14:24 UTC, ike709 commented
I wonder if I should actually do it in `LoopContinue()`

2022-03-09 19:48 UTC, wixoaGit requested changes

2022-03-09 19:48 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMProcBuilder.cs
> +                    // ProcessStatementSet() needs to be before any loops
This doesn't have any affect. It's just moving the `DMASTProcStatementSet` check outside of `ProcessStatement()`, it's still being processed in the same order.

2022-03-13 02:36 UTC, wixoaGit approved these changes
In the future it'd be better to have a sleep opcode instead of depending on the runtime implementing a `sleep()` proc, but this works for now.

2022-03-13 02:36 UTC, merged