Error tolerance refactor for map parsing/saving
wixoaGit/OpenDream pull request #614
Opened 2022-03-06 10:20 UTC by ike709

I'll come back and write a proper desc when it isn't 4am.

2022-03-06 10:20 UTC, ike709 commented
Good to go, just need to write the desc.

2022-03-06 21:33 UTC, ike709 commented
There.

2022-03-18 00:54 UTC, wixoaGit requested changes

2022-03-18 00:54 UTC, wixoaGit commented on DMCompiler/Compiler/DMM/DMMParser.cs
> +                            }
Might be better to move this warning into `AddVarOverride()` itself. DM code can also override the same var multiple times.

2022-03-18 00:54 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +                DMCompiler.Warning(new CompilerWarning(Location, $"DMM overrides for expression {GetType()} are not implemented"));
```suggestion
                DMCompiler.Warning(new CompilerWarning(Location, "DMM overrides for newlist() are not implemented"));
```

2022-03-18 00:54 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Procs.cs
> +        }
Proc calls cannot be serialized into json. Was this added because of a `rgb()` call or similar?

2022-03-18 00:54 UTC, wixoaGit commented on DMCompiler/DMCompiler.cs
>                  List<DreamMapJson> maps = ConvertMaps(preprocessor.IncludedMaps);
Compiling should exit early if `ErrorCount > 0` after converting the maps, and not go on to call `SaveJson()`

2022-03-18 00:54 UTC, wixoaGit commented on OpenDreamRuntime/DreamMapManager.cs
> +                Logger.Error("Loading more than one map is not implemented, skipping additional maps");
Seems more like a warning to me
```suggestion
                Logger.Warning("Loading more than one map is not implemented, skipping additional maps");
```

2022-03-18 01:38 UTC, wixoaGit requested changes

2022-03-18 01:38 UTC, wixoaGit commented on DMCompiler/DMCompiler.cs
> +            var beforeErrorCount = DMCompiler.ErrorCount;
`ErrorCount` should always be zero at this point.
```suggestion
```

2022-03-18 01:38 UTC, wixoaGit commented on DMCompiler/DMCompiler.cs
> +            if (DMCompiler.ErrorCount == beforeErrorCount)
```suggestion
            if (ErrorCount > 0)
```

2022-03-18 02:01 UTC, wixoaGit approved these changes

2022-03-18 02:01 UTC, merged