Makes using an upward search operator in an expression work
wixoaGit/OpenDream pull request #618
Opened 2022-03-07 07:05 UTC by ike709

Fixes #617

2022-03-08 12:26 UTC, ike709 commented on DMCompiler/DM/Visitors/DMVisitorExpression.cs
> +                if (truePath.FindElement("proc") == -1)
```suggestion
                // Skip procs and verbs
                if (truePath.FindElement("proc") == -1 && truePath.FindElement("verb") == -1)
```

2022-03-20 04:32 UTC, wixoaGit requested changes
A better way to handle this would be to add support in the parser for `DMASTUpwardPathSearch` without a path on the left side, implicity using the current path.

Having `DownwardSearch` and `UpwardSearch` path types is actually an incorrect representation of what's going on and I plan to have them removed at some point.

2022-03-28 02:00 UTC, ike709 commented
Seems to work

2022-03-28 02:05 UTC, ike709 commented
Nevermind then.

2022-03-28 02:06 UTC, ike709 commented
Going to just give up on this for now.

2022-03-28 02:06 UTC, closed without merging