Implements DreamMetaObjectIcon, Width(), Height()
wixoaGit/OpenDream pull request #650
Opened 2022-03-27 08:16 UTC by ike709

See #141 

This is some messy 3am coding, opening as a draft to make my life easier.

2022-03-30 03:54 UTC, ike709 commented
Probably good to review.

2022-03-30 06:58 UTC, ZeWaka commented on OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs
> +                // TODO confirm BYOND behavior of invalid types
For the 'no name' empty icon state, it's an empty string. Default frames and dirs is 1. Moving default is null.
```
# BEGIN DMI
version = 4.0
	width = 32
	height = 192
state = "heavenlight"
	dirs = 1
	frames = 1
state = ""
	dirs = 1
	frames = 1
# END DMI
```
for 
![image](https://user-images.githubusercontent.com/4741640/160770287-be0577ec-701c-45b3-a152-275c7a5b1b78.png)

Interesting tidbit: All trailing and preceding spaces in an icon state are invalid, and trimmed in DM.

2022-05-10 23:19 UTC, wixoaGit requested changes

2022-05-10 23:19 UTC, wixoaGit commented on OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs
> +                if (rsc is ConsoleOutputResource)
```suggestion
                if (Path.GetExtension(rsc.ResourcePath) != ".dmi")
```

2022-05-10 23:19 UTC, wixoaGit commented on OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs
> +                        dreamObject.SetVariableValue("icon", new DreamValue(fileString));
`/icon.icon` isn't the icon path. It seems to be some kind of internal structure, `usr << I.icon` leads to a "bad output value" error.
```suggestion
```

2022-05-10 23:19 UTC, wixoaGit commented on OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs
> +                dreamObject.SetVariableValue("icon", new DreamValue(rsc.ResourcePath));
```suggestion
```

2022-05-10 23:22 UTC, wixoaGit commented on OpenDreamRuntime/Objects/MetaObjects/DreamMetaObjectIcon.cs
> +            public DreamIconObject(DreamResource rsc, DreamValue? state, DreamValue? dir, DreamValue? frame, DreamValue? moving)
No uses of this ever pass `null` values, these DreamValues don't need to be nullable.

2022-05-11 03:50 UTC, wixoaGit approved these changes

2022-05-11 03:50 UTC, merged