Improves bad proc arg handling
wixoaGit/OpenDream pull request #655
Opened 2022-04-02 11:43 UTC by ike709

Fixes #265 

The error now matches BYOND (with the addition of the token string for the bad arg). Unlike BYOND it also errors for http://www.byond.com/forum/post/2736128

Error recovery should be robust enough to not need to skip.

Coded this at 4am so it's entirely possible that it could be done more efficiently, but it works and it's an error branch.

2022-04-07 01:00 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    }
```suggestion
```

2022-05-13 23:50 UTC, wixoaGit requested changes

2022-05-13 23:50 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                // Breaking change - BYOND doesn't specify the arg
Is this really a "breaking" change?

2022-05-13 23:50 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                if (Current().Type != TokenType.DM_RightParenthesis && Current().Type != TokenType.DM_Comma && !Check(TokenType.DM_IndeterminateArgs))
`DefinitionParameters()` is intended to only parse the vars (`var/a, var/b, var/c`) and not the parentheses. This check (and others) should be moved to `ProcCall()`.

2022-05-15 01:01 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                // Breaking change - BYOND doesn't specify the arg
```suggestion
                // BYOND doesn't specify the arg
```

2022-06-16 02:38 UTC, Hinaichigo commented
Will this also fix the error `Duplicate argument "null"` when `null` is passed as an arg multiple times to a proc?

2022-06-16 03:02 UTC, wixoaGit commented
> Will this also fix the error `Duplicate argument "null"` when `null` is passed as an arg multiple times to a proc?

Are you talking about procs defined like this?

`/proc/foo(null, null)`

If so, this won't fix that. It was an intentional decision to make 2 arguments with the same name a compile error. These are also not null values being passed to the proc, this is creating a var named `null` that shadows (and replaces) any uses of `null` which is likely unintentional.

2022-06-16 03:10 UTC, Hinaichigo commented
That's what I meant, yeah.
So allowing things like:
```
/obj/item/weapon/sword/executioner/afterattack(null, mob/living/user as mob|obj, null, null, null)
	if(complete)
		user.delayNextAttack(30) //thrice the regular attack delay
```
is another silent error with BYOND?

2022-06-16 03:12 UTC, wixoaGit commented
> That's what I meant, yeah. So allowing things like:
> 
> ```
> /obj/item/weapon/sword/executioner/afterattack(null, mob/living/user as mob|obj, null, null, null)
> 	if(complete)
> 		user.delayNextAttack(30) //thrice the regular attack delay
> ```
> 
> is another silent error with BYOND?

Yes, multiple parameters with the same name doesn't raise any errors in BYOND. Naming a parameter `null` is actually another issue.

2022-06-16 03:12 UTC, ike709 commented
Correct

2022-06-16 03:13 UTC, Hinaichigo commented
So it's an issue masked by another issue. That makes sense.

2022-07-12 21:09 UTC, wixoaGit requested changes

2022-07-12 21:09 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                            Error($"error: {parameters.Last().Name}: missing comma ',' or right-paren ')'", false);
`parameters.Last()` throws an exception if there aren't any parameters.

For example: `proc/t(`

2022-07-14 01:35 UTC, wixoaGit approved these changes

2022-07-14 01:35 UTC, merged