Implements multi-dimensional lists in PathArray()
wixoaGit/OpenDream pull request #659
Opened 2022-04-05 19:28 UTC by ike709

Closes #657 

I don't see where `list doubly initialized` is printed instead of just overriding the value.

2022-04-05 19:29 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                if (!path.Elements[..^1].Contains("list")) {
```suggestion
                // Trying to use path.IsDescendantOf(DreamPath.List) here doesn't work
                if (!path.Elements[..^1].Contains("list")) {
```

2022-05-20 15:47 UTC, wixoaGit commented
> I don't see where list doubly initialized is printed in BYOND instead of just overriding the value.

This warning gets printed when there is both a list size and an initializer
`var/L[0] = 3`

2022-05-20 15:59 UTC, wixoaGit commented
Some testing in Dream Maker shows that empty list sizes (`var/L[]`) does nothing but ensure the var's type is `/list`. `var/L[][][][10]` only creates a 1-dimensional list of size 10, and `var/L[][2][][10]` creates a 2-dimensional list of size 2 and 10. This implementation doesn't have that behavior.

2022-05-29 03:28 UTC, wixoaGit requested changes
Some testing in Dream Maker shows that empty list sizes (`var/L[]`) do nothing but ensure the var's type is /list. `var/L[][][][10]` only creates a 1-dimensional list of size 10, and `var/L[][2][][10][]` creates a 2-dimensional list of size 2 and 10. This implementation doesn't have that behavior.

2022-05-30 01:13 UTC, ike709 commented
Note to myself: Right now opendream doesn't really handle multidimensional lists properly and it needs a new expression to support them.

2022-05-30 03:45 UTC, ike709 commented
Should match BYOND now

2022-06-07 04:25 UTC, wixoaGit requested changes

2022-06-07 04:25 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMAST.cs
> +        public DMASTPath Path;
This property is unnecessary, it's always going to be creating a `/list`

2022-06-07 04:25 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMAST.cs
> +        public DMASTCallParameter[] Dimensions;
This could be `DMASTExpression[]`. There's no need to turn them into parameters.

2022-06-07 04:25 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +        DreamPath TargetPath;
This property isn't needed or used.

2022-06-07 04:25 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +            Arguments.EmitPushArguments(dmObject, proc);
There's no need to turn the sizes into arguments. You could keep a list of all the expressions, push them onto the stack, and give the `CreateMultidimensionalList` opcode an immediate value describing how many dimensions (a.k.a expressions pushed onto the stack) there are.

2022-06-11 21:12 UTC, wixoaGit requested changes

2022-06-11 21:12 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                List<DMASTCallParameter> sizes = new List<DMASTCallParameter>(2); // Most common is 1D or 2D lists
This should be converted to a `List<DMASTExpression>`

2022-06-11 21:12 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                bool setSize = false;
This can be removed and replaced with `sizes.Count > 0`

2022-06-11 21:12 UTC, wixoaGit commented on DMCompiler/DM/DMProc.cs
> +            GrowStack(1);
This pops `count` values off the stack and pushes 1
```suggestion
            ShrinkStack(count - 1);
```

2022-06-11 21:12 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +            }
There's no need for two loops here. Non-integer sizes are also accepted and are treated as zero.
```suggestion
            List<int> sizes = new List<int>(count);
            for (var i = 0; i < count; i++)
            {
                state.Pop().TryGetValueAsInteger(out var size);
                sizes.Add(size);
            }
```

2022-06-12 00:36 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    DMASTExpression[] expressions = new DMASTExpression[sizes.Count];
```suggestion
                    DMASTExpression[] expressions = sizes.ToArray()
```

2022-06-12 00:38 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    }
```suggestion
```

2022-06-12 00:39 UTC, wixoaGit approved these changes

2022-06-12 00:53 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    DMASTExpression[] expressions = sizes.ToArray()
```suggestion
                    DMASTExpression[] expressions = sizes.ToArray();
```

2022-06-12 00:58 UTC, merged