Misc cleanup
wixoaGit/OpenDream pull request #660
Opened 2022-04-05 21:53 UTC by ike709

Shaves off ~100 MB and 1-2 seconds from Paradise compilation.

2022-04-06 02:50 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParser.cs
> +            TokenType.DM_Throw
```suggestion
            TokenType.DM_Throw,
            TokenType.DM_Null
```

2022-04-06 02:51 UTC, ike709 commented
Added `null` to the typepath tokens, since apparently it counts as one in BYOND.

2022-04-06 05:13 UTC, wixoaGit requested changes

2022-04-06 05:13 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    if (interpolationValues is null || interpolationValues.Count == 0) {
As long as `interpolationValues` isn't null it should have at least 1 value

```suggestion
                    if (interpolationValues is null) {
```

2022-04-07 03:48 UTC, wixoaGit approved these changes

2022-04-07 03:48 UTC, merged