Moves procs to a single global list/array
wixoaGit/OpenDream pull request #672
Opened 2022-05-01 22:35 UTC by ike709

First step to nuking `DreamPath`. Changes to `call()()` are getting punted to a follow-up PR.

Probably has broken/bad things in here but TestGame seems to work.

2022-05-30 04:43 UTC, Hinaichigo commented
Would this fix certain procs not being recognized even though they are declared elsewhere?

2022-05-30 14:02 UTC, wixoaGit commented
> Would this fix certain procs not being recognized even though they are declared elsewhere?

No, this just changes how existing procs are referenced internally. Could you open an issue for this?

2022-06-05 22:48 UTC, wixoaGit requested changes

2022-06-05 22:48 UTC, wixoaGit commented on DMCompiler/DM/DMProc.cs
> +        private DMObject _dmObject;
Move this down with the rest of the private properties.

2022-06-05 22:48 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMObjectBuilder.cs
> +            // TODO Nuke this pass
Extra line here
```suggestion
            ProcessFile(astFile);

            // TODO Nuke this pass
```

2022-06-10 03:26 UTC, wixoaGit requested changes

2022-06-10 03:26 UTC, wixoaGit commented on DMCompiler/DM/DMObject.cs
>                  }
```suggestion
                typeJson.Procs = new List<List<int>>(Procs.Values);
```

2022-06-10 04:25 UTC, wixoaGit approved these changes

2022-06-10 04:26 UTC, merged