Re-adds unit tests
wixoaGit/OpenDream pull request #673
Opened 2022-05-03 17:03 UTC by ike709

I commented out all of the broken ones. Getting the test framework back in is more important that fixing every test, we can address those later.

2022-05-05 18:35 UTC, wixoaGit requested changes

2022-05-05 18:35 UTC, wixoaGit commented on Content.Tests/SetupCompileDM.cs
> +// This it outside of any namespace so it affects the whole assembly.
```suggestion
// This is outside of any namespace so it affects the whole assembly.
```

2022-05-05 18:35 UTC, wixoaGit commented on OpenDreamRuntime/EntryPoint.cs
> +            _dreamManager.Initialize(null);
Have this call pass the cvar instead of having multiple locations default to `testingJson ?? _configManager.GetCVar<string>(OpenDreamCVars.JsonPath)`

2022-05-05 22:51 UTC, wixoaGit requested changes

2022-05-05 22:51 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +        public void Initialize(string? testingJson) {
This is more than just the testing json now, and shouldn't be null.
```suggestion
        public void Initialize(string jsonPath) {
```

2022-05-05 22:51 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +            DreamCompiledJson json = LoadJson(testingJson);
```suggestion
            DreamCompiledJson json = LoadJson(jsonPath);
```

2022-05-05 22:51 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +            _dreamResourceManager.Initialize(testingJson);
```suggestion
            _dreamResourceManager.Initialize(jsonPath);
```

2022-05-05 22:51 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +            }
Is this still an issue?

2022-05-05 23:53 UTC, ike709 commented on OpenDreamRuntime/DreamManager.cs
> +            }
No

2022-05-06 00:01 UTC, wixoaGit approved these changes

2022-05-06 00:01 UTC, merged