Cope with whitespace in ExpressionPrimary
wixoaGit/OpenDream pull request #695
Opened 2022-05-16 22:32 UTC by ike709

Paradise:
```
/proc/is_surgery_tool(obj/item/W as obj)
	return (	\
	istype(W, /obj/item/scalpel)			||	\
	istype(W, /obj/item/hemostat)		||	\
	istype(W, /obj/item/retractor)		||	\
	istype(W, /obj/item/cautery)			||	\
	istype(W, /obj/item/bonegel)			||	\
	istype(W, /obj/item/bonesetter)
	)
```

2022-05-23 05:11 UTC, Hinaichigo commented
What does the backslash do here?

2022-05-23 05:13 UTC, ZeWaka commented
escapes the newline

2022-05-29 21:58 UTC, wixoaGit requested changes

2022-05-29 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                Whitespace(includeIndentation: true);
`BracketWhitespace()` is meant to be used for whitespace inside brackets/parentheses which allows delimiters. The first `Whitespace()` here should be changed too.
```suggestion
                BracketWhitespace();
                DMASTExpression inner = Expression();
                BracketWhitespace();
```

2022-05-30 00:23 UTC, wixoaGit approved these changes

2022-05-30 00:30 UTC, merged