Implement `global.vars`
wixoaGit/OpenDream pull request #697
Opened 2022-05-17 02:28 UTC by ike709

Closes #691 

Dunno if this is the best way to do it but it works.

2022-07-02 19:35 UTC, wixoaGit requested changes

2022-07-02 19:35 UTC, wixoaGit commented on DMCompiler/DM/Expressions/LValue.cs
> +            : base(location, path) {
```suggestion
        public GlobalVars(Location location)
            : base(location, null) {
```

2022-07-02 19:35 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMVisitorExpression.cs
> +                Result = new Expressions.GlobalVars(globalIdentifier.Location, null);
```suggestion
                Result = new Expressions.GlobalVars(globalIdentifier.Location);
```

2022-07-02 19:35 UTC, wixoaGit commented on OpenDreamRuntime/Objects/DreamList.cs
> +            list.InitSpawn(new DreamProcArguments(null));
There's no need to initialize a DreamList after creating it.
```suggestion
```

2022-07-02 19:35 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +            var list = state.DreamManager.Globals.GetRange(1, state.DreamManager.Globals.Count - 1);
This is unused
```suggestion
```

2022-07-02 19:35 UTC, wixoaGit commented on OpenDreamRuntime/Objects/DreamList.cs
> +
This is unused
```suggestion
```

2022-07-03 18:14 UTC, ike709 commented on OpenDreamRuntime/Objects/DreamList.cs
> +        public override void SetValue(DreamValue key, DreamValue value) {
```suggestion
        public override void SetValue(DreamValue key, DreamValue value, bool allowGrowth = false) {
```

2022-07-05 02:56 UTC, wixoaGit approved these changes

2022-07-05 02:56 UTC, merged